### ISSUE TITLE
Can't recruit from the beach

### ISSUE THREAD

**Issue by AndyHunt66** [AntonioSoler/bga-takaraisland#5]
I have 7 gold and have not yet recruited my third adventurer from the beach.
At the end of my turn, when it says 
"You can pay the hospital or recruit one worker on the beach, when done press: End Turn"

if I click on the adventurer on the beach, I get the error:
```

Javascript error:
During callback: onclick / recruit
_1ea.remove is not a function
TypeError: _1ea.remove is not a function
at Object.disconnect (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:48616)
at Object.recruit (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/games/takaraisland/999999-9999//takaraisland.js?1491765761790:1086:9)
at Object. (http://en.1.studio.boardgamearena.com/takaraisland?table=38005:791:50)
at HTMLDivElement. (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:32185)
Script: 
Url: http://en.1.studio.boardgamearena.com/takaraisland?table=38005
U=2303476
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Javascript error:
During callback: onclick / recruit
_1ea.remove is not a function
TypeError: _1ea.remove is not a function
at Object.disconnect (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:48616)
at Object.recruit (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/games/takaraisland/999999-9999//takaraisland.js?1491765761790:1086:9)
at Object. (http://en.1.studio.boardgamearena.com/takaraisland?table=38005:791:50)
at HTMLDivElement. (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:32185)
Script: 
Url: http://en.1.studio.boardgamearena.com/takaraisland?table=38005
U=2303476
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Javascript error:
During callback: onclick / recruit
_1ea.remove is not a function
TypeError: _1ea.remove is not a function
at Object.disconnect (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:48616)
at Object.recruit (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/games/takaraisland/999999-9999//takaraisland.js?1491765761790:1086:9)
at Object. (http://en.1.studio.boardgamearena.com/takaraisland?table=38005:791:50)
at HTMLDivElement. (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:32185)
Script: 
Url: http://en.1.studio.boardgamearena.com/takaraisland?table=38005
U=2303476
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
```

and the adventurer is not recruited

**Comment by AntonioSoler** [comment]
fixed in  	2e4aebc
